### ISSUE TITLE
Focus on "Next" pagination button not cleared after click

### ISSUE THREAD

**Issue by frodopwns** [romansanchez/Calaca#12]
When you have multiple pages of data returned in your results and you click the "Next" button it retains its focus until you click somewhere on the DOM.

![Image of Issue](http://i.imgur.com/eTl5VAZ.png)

**Comment by romansanchez** [comment]
Looks like you've modified the button styles. Can you share the css for your buttons?

**Comment by frodopwns** [comment]
I think it is related to this: https://github.com/angular/material/issues/556
but I'm not entirely sure what was changed in the css so I guess it could be.

**Comment by frodopwns** [comment]
```css
#pagination-details {
  float: right;
}
.results {
  width: 860px;
  margin-left: auto;
  margin-right: auto;
  background-color: #fff;
  border-radius: 5px;
}
.pagination-controls {
  width: 860px;
  height: 30px;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}
.pager {
  height: 30px;
  width: 75px;
  border-radius: 25px;
  background-color: #000;
  border: none;
  color: #fff;
  margin: 5px;
}
.pager:hover,
.pager:focus {
  cursor: pointer;
  background-color: #565A5C;
}
.pager:focus {
  outline:0;
}
```
